"""
vibration-anomaly-lab -- group leakage, operating-point conditioning, and what
to ship when the positive class has two members.

The five modules map onto the five decisions the problem forces:

    features.py          what one trial is worth measuring by
    conditioning.py      what "abnormal" means when the operating point dominates
    validation.py        what counts as an honest score, and at what granularity
    production_model.py  what to do when the validation set is too small to
                         choose a model
    metric_design.py     how much a published score reveals about the hidden
                         labels, and which defences actually narrow the channel

Demo entry points::

    python3 -m vibration_anomaly_lab.production_model
    python3 -m vibration_anomaly_lab.metric_design

All data in this repository is synthetic and generated by
``data/make_synthetic_data.py``.  The published protocol metrics are re-derived by
``verify_claims.py`` at the repository root, which imports nothing from here on
purpose -- a verification script that shares code with the thing it verifies
verifies less than it appears to.
"""
from __future__ import annotations

from .conditioning import ConditionalRobustZ, conditional_robust_z, healthy_reference
from .features import (
    AXES,
    STATS,
    raw_features,
    trial_features,
    unit_labels,
    vibration_features,
)
from .validation import (
    best_unit_f1,
    leave_one_unit_out,
    max_margin_threshold,
    random_kfold_over_trials,
    unit_f1_at,
    unit_report,
    unit_scores,
    unit_truth,
)


# ``production_model`` is imported lazily.  It is the only module that pulls in
# scikit-learn estimators, and keeping it out of the package import cycle lets
# ``python3 -m vibration_anomaly_lab.production_model`` run its demo without
# re-entering itself.
def __getattr__(name: str):
    if name in {"ProductionModel", "UnitDecision", "Evidence"}:
        from . import production_model as _pm

        return getattr(_pm, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "AXES",
    "STATS",
    "ConditionalRobustZ",
    "Evidence",
    "ProductionModel",
    "UnitDecision",
    "best_unit_f1",
    "conditional_robust_z",
    "healthy_reference",
    "leave_one_unit_out",
    "max_margin_threshold",
    "random_kfold_over_trials",
    "raw_features",
    "trial_features",
    "unit_f1_at",
    "unit_labels",
    "unit_report",
    "unit_scores",
    "unit_truth",
    "vibration_features",
]
